name: TownyWars
version: 1.2.0-1.15
main: com.etysoft.townywars.TownyWars
authors: [karlov_m]
depend: [Towny]
description: A simple arcade plugin for wars with Towny.
commands:
  townwars:
    description: TownyWars main command
    usage: /<command>
    aliases: twar
permissions:
  townywars.admin:
    default: op
    children:
      aun.info: true
      aun.edittown: true
    description: Allows all commands
  townywars.use:
    default: op
    description: Simple information using
  townywars.mayor:
    default: op
    description:  Declare a war and manage it